[Very rough WIP] Olshansky localnet testing
pokt-foundation/pocket-e2e-stack pull request #13
Opened 2021-11-27 16:22 UTC by Olshansk

2021-11-27 19:49 UTC, derrandz reviewed
Oh now I see, I think the seeds thingy is just bcuz of the commented out nodes from debugging the docker issue. Overall I like these changes 👍🏻  and thanks a bunch for the fixes!

2021-11-27 19:49 UTC, derrandz commented on docker/pokt-net/dev-tm/Dockerfile
> +COPY ${POCKET_E2E_STACK_RELATIVE_PATH}/docker/pokt-net/dev-tm/install-deps.sh ${POCKET_CORE_REPO_RELATIVE_PATH}
If this/these images can be able to not know a single thing about their host, that would be great!

I understand this for now until we see what's up with this update.

2021-11-27 19:49 UTC, derrandz commented on docker/pokt-net/dev-tm/prepare-tendermint.sh
>  fi
👍🏻

2021-11-27 19:49 UTC, derrandz commented on docker/pokt-net/dev-tm/watch.sh
> +  export EXECCOMMAND="start --keybase=false --datadir=/home/app/.pocket"
Why did the seeds go?

2021-11-27 19:49 UTC, derrandz commented on pkt-stack.sh
> +if (! docker stats --no-stream ); then
Now that's real nice!

2021-11-27 19:49 UTC, derrandz commented on pkt-stack.sh
> +./bin/pkt-stack pokt-net dev-tm up
🤔  more like pokt-net-stack.sh

2021-11-27 19:49 UTC, derrandz commented on stacks/pokt-net/dev-tm/.nodea.dev.env
> +# POCKET_CORE_SEEDS='fcf719ca739dccbc281b12bc0d671aaa7a015848@nodeb.dev.pokt:26656,35df1afa3f2156cedaebe2e3a8e831b92c3a5ae3@nodec.dev.pokt:26656'
Wsup with the seeds?

2021-11-27 19:49 UTC, derrandz commented on stacks/pokt-net/shared/chains.json
> +      "password": ""
That's awesome!

2021-11-29 16:20 UTC, derrandz requested changes
Since you've last opened this, I've been able to run fine with the prelease as recommended in the [issue](https://github.com/docker/compose/issues/8971) you have opened.

You can later rebase this with main to keep chains.json and other docker sanity checks.

2021-11-29 16:20 UTC, derrandz commented on stacks/pokt-net/dev-tm/up.sh
> -
This is actually very much required and I want it to not be part of the container build phase.

2021-11-29 20:45 UTC, Olshansk commented on docker/pokt-net/dev-tm/Dockerfile
> +COPY ${POCKET_E2E_STACK_RELATIVE_PATH}/docker/pokt-net/dev-tm/install-deps.sh ${POCKET_CORE_REPO_RELATIVE_PATH}
Yea, I wasn't a fan of this either...

What I ended up doing is updating the stack.yml (which is filesystem aware) to have `POCKET_E2E_STACK_RELATIVE_PATH=${POCKET_E2E_STACK_RELATIVE_PATH}/docker/pokt-net/dev-tm` so the Dockerfile would only have `${POCKET_E2E_STACK_RELATIVE_PATH}/install-deps.sh`.

It's not perfect, but I do think its cleaner. Wdyt?

2021-11-29 20:45 UTC, Olshansk commented on docker/pokt-net/dev-tm/watch.sh
> +  export EXECCOMMAND="start --keybase=false --datadir=/home/app/.pocket"
I commented it out when debugging a single node, but restored.

2021-11-29 20:46 UTC, Olshansk commented on pkt-stack.sh
> +./bin/pkt-stack pokt-net dev-tm up
Renamed to `pokt-net-dev-tm.sh`

2021-11-29 20:46 UTC, Olshansk commented on stacks/pokt-net/dev-tm/.nodea.dev.env
> +# POCKET_CORE_SEEDS='fcf719ca739dccbc281b12bc0d671aaa7a015848@nodeb.dev.pokt:26656,35df1afa3f2156cedaebe2e3a8e831b92c3a5ae3@nodec.dev.pokt:26656'
Reversed!

2021-11-29 20:52 UTC, Olshansk commented
@derrandz Regarding the partial refactoring I did to work around the docker-compose bug, I'd still like to keep it. It avoids the need to copy-around local files and pollutes the pocket-core repo, and I think it makes more sense conceptually from a context/Dockerfile perspective.

2021-11-29 20:53 UTC, Olshansk commented on stacks/pokt-net/dev-tm/up.sh
> -
We might need to sync up on this offline. This copied files over from `pocket-e2e-stack` to `pocket-core` and then did a COPY inside the Dockerfile. After removing this script and updating the context, it just does a direct copy from pocket-e2e-stack into the dev container. Does that make sense?

2021-11-29 21:57 UTC, derrandz commented on stacks/pokt-net/dev-tm/up.sh
> -
It does, and it is much cleaner! Thanks!

2021-11-29 22:09 UTC, derrandz approved these changes
Small changes but good to go 👍🏻 

Thank you @Olshansk this was a pleasure to look at

2021-11-29 22:09 UTC, derrandz commented on bin/pokt-net-dev-tm.sh
> +function check_docker() {
😵

2021-11-29 22:09 UTC, derrandz commented on docs/run-localnet.md
> +bin/pkt-stack pokt-net dev up
sweet! let's just add `pokt-net dev-tm` to them (_that's the stack that includes tendemrint_)

2021-11-29 22:09 UTC, derrandz commented on stacks/pokt-net/dev-tm/stack.yml
> +      dockerfile: pocket-e2e-stack/docker/pokt-net/dev-tm/Dockerfile
Perhaps let's `pwd` it but keep only the last name since everybody will have a different folder name

2021-11-29 22:09 UTC, derrandz commented on stacks/pokt-net/dev-tm/stack.yml
> +      - ${CWD}/data/pokt-net.nodec.pokt.dev:/home/app/.pocket/data
👍🏻

2021-11-30 00:18 UTC, merged