Feat: Add playground
pokt-foundation/pocket-e2e-stack pull request #18
Opened 2021-12-01 23:20 UTC by derrandz

Changes:

- [ ] Add playground as submodule
- [ ] Add script to launch the playground as pocket stack
- [ ] Add script to launch the playground's monitoring alongside any other stack

2021-12-02 04:15 UTC, Olshansk requested changes

2021-12-02 04:15 UTC, Olshansk commented on .playground.env.example
> +DOMAIN=mainnet.pokt.network.
Remove period at the end

2021-12-02 04:15 UTC, Olshansk commented on .playground.env.example
> +PEER_PORT=21056
We've been using a different one up until now so just wanted to double check that this is correct?

2021-12-02 04:15 UTC, Olshansk commented on .playground.env.example
> +NODE_N=0-5
There are only 3 seeds in SEEDS but we're creating 5 nodes?

2021-12-02 04:15 UTC, Olshansk commented on .playground.env.example
> +SNAPSHOT_URL=https://link.us1.storjshare.io/raw/jxswez33rp3jebf5sakbycrkksya/pocket-public-blockchains/pocket-network-data-1229-rc-0.6.3.6.tar
@aqt01 Is there a snapshot URL for 0.6.4? I think it needs to match the pocket image below.

2021-12-02 04:15 UTC, Olshansk commented on Makefile
> +
Remove extra whitelines.

2021-12-02 04:15 UTC, Olshansk commented on bin/pokt-net-playground.sh
> +source_and_export_env() {
Should add a TODO to extract these helpesr into a utils file.

2021-12-02 04:15 UTC, Olshansk commented on bin/pokt-net-playground.sh
> +# Call the pokt-net stack.
Should we call it the playground stack? Or maybe call it `pokt-net/playgroudn` instead of `pokt-net` full?

2021-12-02 04:15 UTC, Olshansk commented on stacks/pokt-net/full/up.sh
> +#!/usr/bin/env bash
Per my comment above, s/full/playgroudn?

2021-12-02 04:15 UTC, Olshansk commented on bin/pokt-net-playground.sh
> +  ./bin/pkt-stack pokt-net scaffold up
Ahh, so is the scaffolder responsible for configuring everything for playground?

2021-12-02 11:44 UTC, derrandz commented on .playground.env.example
> +PEER_PORT=21056
I am not sure, this was a copy-paste from Lowell's environment

2021-12-02 11:45 UTC, derrandz commented on .playground.env.example
> +NODE_N=0-5
I think you can seed off of any number you like, like, use one mainnet seed for all of yours nodes

2021-12-02 11:45 UTC, derrandz commented on .playground.env.example
> +SNAPSHOT_URL=https://link.us1.storjshare.io/raw/jxswez33rp3jebf5sakbycrkksya/pocket-public-blockchains/pocket-network-data-1229-rc-0.6.3.6.tar
Good call 👍🏻

2021-12-02 11:45 UTC, derrandz commented on Makefile
> +
What a waste of good space!

2021-12-02 11:45 UTC, derrandz commented on bin/pokt-net-playground.sh
> +source_and_export_env() {
👍🏻

2021-12-02 11:46 UTC, derrandz commented on bin/pokt-net-playground.sh
> +# Call the pokt-net stack.
Okay, we are thinking the same thing, but I don't want to add, like, wrappers around `pokt-net playground up` but again these wrappers are needed because of the scripts we are running, so yeah I will look for a nice way to do this

2021-12-02 11:48 UTC, derrandz commented on bin/pokt-net-playground.sh
> +  ./bin/pkt-stack pokt-net scaffold up
Literally, cuz the scaffolder will run your playground auto-gen scripts and output them to a specific path (_for now it's stacks/pokt-net/full_) so that you can run `bin/pkt-stack playground up`. This is a starter for now and better ideas can be found tbh

2021-12-03 01:42 UTC, derrandz commented on .playground.env.example
> +PEER_PORT=21056
A different what?

2021-12-05 19:28 UTC, Olshansk commented on .playground.env.example
> +NODE_N=0-5
Yea, makes sense!

2021-12-05 19:29 UTC, Olshansk commented on .playground.env.example
> +PEER_PORT=21056
@aqt01 ?

2021-12-05 22:06 UTC, Olshansk requested changes
Requested a few minor changes, but just wanted to add a few more comments here.

1.`POCKET_CORE_PASSPHRASE_NODE[0-10]` aren't specified anywhere. Should we just use the same one (i.e. `Yo` everywhere and not need to customize it?

2. This is just tooling and not mission critical, so feel free to reject some of the comments I made through the PR. Most comments are just suggestions/ideas rather than requests. I will be explicit in the future when something is a "must".

3. I update the PR description per some changes I had to make, please review.

4. I tested on my machine, but the default config doesn't bring up grafana and prometheus. I will look into this...

2021-12-05 22:16 UTC, Olshansk commented on bin/pokt-net/playground.sh
> +      ./bin/pkt-stack pokt-net playground up
Shouldn't we always be running this if the user chose `up` as the option instead of scaffold?

Maybe we can just simplify it to `./bin/pkt-stack pokt-net scaffold` and `./bin/pkt-stack pokt-net scaffold up` without the need for the env variable at all?

2021-12-05 22:20 UTC, Olshansk commented on stacks/pokt-net/scaffold/up.sh
> +echo "Copying playground .env to proper path..."
Should this be called before the docker-compose command?

2021-12-06 20:32 UTC, Olshansk commented on .gitignore
> +.playground.env
Done.

2021-12-07 00:17 UTC, derrandz commented on bin/pokt-net/playground.sh
> +      echo "You have to scaffold your playground before you can use it";
It's in `docs/scaffold-playground.md`

2021-12-07 00:17 UTC, derrandz commented on bin/pokt-net/playground.sh
> +  WANT_TO_SCAFFOLD=$([ "$?" == 0 ] && echo 1 || echo 0)
True that, but we'll have to update `quiet_check_env_var` to return both values. Noted, will do.

2021-12-07 00:17 UTC, derrandz commented on bin/pokt-net/playground.sh
> +    if [[ $? != 1 ]]; then
Indeed, it feels volatile and will become volatile before we know it. Can definitely become a todo until I refactor the verify_scaffolding to return desired outputs. Noted.

2021-12-07 00:17 UTC, derrandz commented on stacks/pokt-net/playground/down.sh
> +  --project-directory $CWD/stacks/pokt-net/full \
No, because the `bin/...` scripts run from the CWD perspective, and call on these scripts that are in `$CWD/stacks/stack_name/env_name/(up|down|config).sh`.

The reason behind having it run like that was so that docker-compose could access `$CWD/docker` and other directories, but because it also is easier to ready and keeps the global scope in perspective. I prefer this to isolated scopes within folders when some stacks (_and their docker-compose files_) end up using other files/directories from `$CWD`.

What do you think?

2021-12-07 00:17 UTC, derrandz commented on stacks/pokt-net/playground/up.sh
> +  --project-directory $CWD/stacks/pokt-net/full \
Ditto'd the ditto above

2021-12-07 00:17 UTC, derrandz commented on stacks/pokt-net/scaffold/cleanup.sh
> +  for i in "${!paths[@]}"
So when it's list of `node1 node2 node3`, it works, notice this [line)(https://github.com/pokt-foundation/pocket-e2e-stack/pull/18/files#diff-b62c118b68280287f33f35f16d9348dd093222b03edce7dcf394e9e8e56b72afR11).

It worked just fine in my machine, can you try it?

2021-12-07 00:17 UTC, derrandz commented on stacks/pokt-net/scaffold/stack.yml
> +      context: ${POCKET_CORE_REPOS_PATH}/${POCKET_E2E_STACK_RELATIVE_PATH}/playground
Correct 👍🏻

2021-12-07 00:17 UTC, derrandz commented on stacks/pokt-net/scaffold/stack.yml
> +      - ${POCKET_CORE_REPOS_PATH}/${POCKET_E2E_STACK_RELATIVE_PATH}/stacks/pokt-net/full:/pocket
Agreed

2021-12-07 00:17 UTC, derrandz commented on stacks/pokt-net/scaffold/up.sh
> +  for i in "${!paths[@]}"
I suppose `${!array[@]}` returns indexes available in the array such that `i` takes up those index values.

2021-12-07 00:17 UTC, derrandz commented on stacks/pokt-net/scaffold/up.sh
> +nodes=$(ls $CWD/stacks/pokt-net/full | grep node | awk '{print $1}')
Noted 👍🏻

2021-12-07 04:09 UTC, merged